name: Build
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ macos-13, windows-latest ]
        include:
          - os: macos-13
            release_args: --onedir, --icon resources/QFIcon.icns
            package_name: macos-binary
          - os: windows-latest
            release_args: --onefile, --icon resources/QFIcon.ico
            package_name: windows-binary
    runs-on: ${{ matrix.os }}
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          spec: 'QuantiFish.py'
          requirements: './requirements.txt'
          options: --name "QuantiFish", --windowed, --add-data resources:resources, ${{ matrix.release_args }}
      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package_name }}
          path: dist/QuantiFish.*
          retention-days: 30
  publish-pypi:
    name: Pypi
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-binary/*.exe
            macos-binary/*.zip
          draft: true
          fail_on_unmatched_files: true
